### PR TITLE
Dataflow e2e test fixes

### PR DESCRIPTION
**Pull request by terryyylim**
**What this PR does / why we need it**:
Fixes bugs introduced by #675 .
- Points prow job for e2e dataflow test to use the correct config files.
- Removes typo that causes docker image creation to fail for prow presubmit job.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by woop** [comment]
This PR has 18 commits...

**Comment by terryyylim** [comment]
Mistakes earlier with the commit log, my bad.

**Pull request merged**
