### PR TITLE
Docker compose bug fix 

### PR DESCRIPTION
**Pull request by woop**
**What this PR does / why we need it**:

* ~Change docker compose file to use host based. This avoids having an inconsistency between default configuration and docker compose configuration.~
* Fix bug with application.yml typo
* Fix port configuration bug for postgres

**Which issue(s) this PR fixes**:

Hopefully fixes all bugs in #652, but more changes are required to close the issue

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by khorshuheng** [comment]
There is one concern though - host network mode only works on Linux host machine. Mac users will not be able to use this.

**Comment by woop** [comment]
> There is one concern though - host network mode only works on Linux host machine. Mac users will not be able to use this.

Damnit I keep forgetting about that limitation. Isn't there a workaround that doesnt involve using private networks?

**Comment by khorshuheng** [comment]
The workaround i used personally, is to do port mapping on 9092 for Kafka. If i want to test using local jupyter notebook, i edit my etc hosts such that kafka:9092 points to localhost:9092 (so that it matches the advertised listener host). I do agree this is not a pretty workaround, though.

**Comment by woop** [comment]
Removed host networking.

**Pull request merged**
