### PR TITLE
v0.3 backport: Fail Spotless check before tests

### PR DESCRIPTION
**Pull request by ches**
**What this PR does / why we need it**:

Backports #487 to `v0.3-branch`—as we are internally developing on this branch for the time being, we're trying to maintain formatting for the sake of easing reviews as intended, and also in hopes that it will ease cherry picks for back- and possible forward-porting since #487 keeps consistency.

I'll send one of these for `v0.4-branch` too, as we are edging closer to catching up to v0.4 🎉 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ches** [comment]
The test failures for Java say:

```
 .prow/scripts/test-end-to-end-batch.sh only supports Debian stretch.
Please change your operating system to use this script. 
```

Is there configuration somewhere that maybe has the old branches running on old image versions?

**Comment by ches** [comment]
> I'll send one of these for `v0.4-branch` too

Never mind, @davidheryanto did this already in #496 🙏

**Comment by ches** [comment]
> Is there configuration somewhere that maybe has the old branches running on old image versions?

I guess it's perhaps these:

https://github.com/gojek/feast/blob/7633912cd8209cece2a21ebe344600342ef1ff9b/.prow/config.yaml#L162-L174

The e2e test scripts have been updated to require Debian Stretch, but `maven:3.6-jdk-8` is based on older, presumably.

**Comment by woop** [comment]
> > Is there configuration somewhere that maybe has the old branches running on old image versions?
> 
> I guess it's perhaps these:
> 
> https://github.com/gojek/feast/blob/7633912cd8209cece2a21ebe344600342ef1ff9b/.prow/config.yaml#L162-L174
> 
> The e2e test scripts have been updated to require Debian Stretch, but `maven:3.6-jdk-8` is based on older, presumably.

I think its actually based on `buster` which is newer. Stretch is older.

Correct me if I am wrong @davidheryanto, but you are using this `base_ref` to point to the older prow build scripts for 0.3, meaning the following script is being executed which requires stretch.
https://github.com/gojek/feast/blob/784c7e0e5fc9ba44e60e32cdfaf2f49f6589c209/.prow/scripts/test-end-to-end-batch.sh

So in theory we should just backport the removal of the stretch requirement or change it to buster?

**Comment by davidheryanto** [comment]
Oh I think Docker image `maven:3.6-jdk-8` has been updated, so now it uses Debian 10 (buster), previously that image was based on Debian 9 (stretch).

I think it should be generally safe to remove the check for Debian version, I put it last time just for completeness.

https://github.com/gojek/feast/blob/v0.3-branch/.prow/scripts/test-end-to-end.sh#L6

I will create a PR to v0.3-branch to remove this check.

**Pull request merged**
