### PR TITLE
Add job identifier to FeatureRow 

### PR DESCRIPTION
**Pull request by mansiib**
Issue #145

### CODE REVIEW

**Comment by tims** [comment]
Does the job id get set by core when it starts the job? if not it wont match Beam's notion of a job name.

**Comment by zhilingc** [comment]
@tims The feast definition of job id is actually the job name (not the job id) and is what we return to the user when they run a job; we map it to the runner's job id internally. Since this will be written to BQ, which is external, it makes sense to use this instead of the runner job id.

**Comment by tims** [comment]
I meant is it the jobId being set as the job name in when you start the runner. I thought it wasn't based on conversations, but it seems that it is:

https://github.com/gojek/feast/blob/c525845b05d73e8ec10511b93c34f3105ae438b8/core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java#L81

**Comment by zhilingc** [comment]
@tims If the user sets it from the API it will be the user provided value, if not ingestion will [generate one](https://github.com/gojek/feast/blob/master/ingestion/src/main/java/feast/ingestion/ImportJob.java#L129).

**Comment by zhilingc** [comment]
@mansiib you probably want to merge in the changes you made in PR #146

**Comment by tims** [comment]
> @tims If the user sets it from the API it will be the user provided value, if not ingestion will [generate one](https://github.com/gojek/feast/blob/master/ingestion/src/main/java/feast/ingestion/ImportJob.java#L129).

That's why I asked

**Comment by zhilingc** [comment]
> > @tims If the user sets it from the API it will be the user provided value, if not ingestion will [generate one](https://github.com/gojek/feast/blob/master/ingestion/src/main/java/feast/ingestion/ImportJob.java#L129).
> 
> That's why I asked

Oh right. Sorry, I can't read apparently. haha. It does, as you've already found out.

**Pull request merged**
