### PR TITLE
move read transforms into "source" package as FeatureSources

### PR DESCRIPTION
**Pull request by tims**
First attempt #61 

/donotmerge

/assign zhilingc

### CODE REVIEW

**Comment by tims** [comment]
/hold cancel

I think this is ready to merge now. This introduces breaking changes, for the import spec for file based imports, the "type" changes like so:

```
type: file, options: { format: csv} ----> type: file.csv
type: file, options: { format: json} ----> type: file.json
```

**Comment by tims** [comment]
@zhilingc @pradithya can you please review this?

**Comment by pradithya** [comment]
> I think this is ready to merge now. This introduces breaking changes, for the import spec for file based imports, the "type" changes like so:
> 
> type: file, options: { format: csv} ----> type: file.csv
> type: file, options: { format: json} ----> type: file.json

I think core will also need to change since it check for the import spec before submitting it, correct @zhilingc ?

**Comment by tims** [comment]
updated core import spec validator class

**Comment by zhilingc** [comment]
Seems good. You're missing the license in some of the files though.
/approve

**Pull request merged**
