### PR TITLE
Database tweaks

### PR DESCRIPTION
**Pull request by smadarasmi**
Some minor tweaks: 
1. feature_id was still referring to old schema -> should be changed to feature_set _id
2. ~ is postgresql specific -> changed to LIKE

### CODE REVIEW

**Comment by zhilingc** [comment]
@smadarasmi 
Since `LIKE` is not the same as `~`, you will need to update the configuration for stores in the end to end tests - the stores should listen for featuresets matching `%:>0` (sql LIKE pattern) rather than `.*:>0` (POSIX regex)

**Comment by ches** [comment]
`SIMILAR TO` is standard SQL but unfortunately doesn't seem widely supported, including by our target RDBMS 😞 Perhaps because the standard specifies a new regex dialect that is not quite POSIX, not many vendors want to bother with it 😩 

`LIKE_REGEX` is standard, using yet another regex dialect, and also not widely supported even by Postgres.

It's unfortunate because I think a `%` glob is probably not as intuitive (nor powerful) of a way to specify a subscription as a regex, but Postgres `~` is definitely not portable.

**Comment by zhilingc** [comment]
I'm all for moving towards something more portable! :) I agree that SQL patterns aren't as ubiquitous as POSIX regex but it's nothing some documentation can't cure.
Just indicating that for this MR to pass some changes need to be made for consistency (and the tests to pass).

**Comment by smadarasmi** [comment]
@zhilingc Sure, I'll do this later today.

**Comment by woop** [comment]
@ches @smadarasmi out of curiousity, which RDBMS are you using?

**Comment by ches** [comment]
> @ches @smadarasmi out of curiosity, which RDBMS are you using?

MS SQL Server. Not Azure but maybe we're providing some degree of insurance that people can run Feast on Azure services 😉

**Comment by woop** [comment]
I'm still wondering if regex is necessary here. It seems like using normal `LIKE` would be more than sufficient, and would probably simplify our API a bit. 

Can I suggest that we only allow wildcards for this RPC? How about:

- Matching a single customer feature set: `customer_transactions`
- Matching many customer feature sets: `customer_*`

Behind the scenes we can replace this with `%` and use `LIKE`.

@zhilingc @ches thoughts?

**Comment by woop** [comment]
I've spoken to @zhilingc and she is fine to move ahead with this. We will limit it to purely wildcards for now, and use `LIKE`. That should make this a much more workable solution for MSSQL.

I will merge this in for now. Of course, this will cause a breaking API change. Master will go into an inconsistent state for a bit, but I have a PR to address that: #309 

Hoping to have that merged in tomorrow. It's close to done.

**Pull request merged**
