### PR TITLE
Fail Spotless formatting check before tests execute

### PR DESCRIPTION
**Pull request by ches**
**What this PR does / why we need it**:

Moves the `spotless:check` Maven goal to execute after tests compile, but before `test` executes the tests. This way the check will be run on CI, which runs `mvn test`, but it doesn't disrupt development flow by failing before compilation (like the `validate` phase would). This strikes a good compromise on failing fast for code standards without being _too_ nagging.

By default, the spotless plugin binds its check goal to the `verify` phase (late in the lifecycle, after integration tests). Because we currently only run `mvn test` for CI (and `package` with `-DskipTests` for E2E), it doesn't proceed as far as `verify` so changes that don't comply get merged. Then, when someone cleans up at a later date by running `spotless:apply` on their branch, [a lot of noisy, unrelated changes come into review][1].

Fortunately a recent PR did run `spotless:apply`, when I run it on this branch the changes are few so it won't create a lot of conflicts for others' outstanding work.

[1]: https://github.com/gojek/feast/pull/466#issuecomment-583329347

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ches** [comment]
Not sure what assigning PRs means for the workflow with the bot. @davidheryanto are we waiting for an `/approve` from you now?

**Comment by davidheryanto** [comment]
I don't think we have any special use of the `assign` feature in GitHub other than for the pull request author to remind/notify the maintainers to review it.

**Comment by ches** [comment]
> I don't think we have any special use of the `assign` feature in GitHub other than for the pull request author to remind/notify the maintainers to review it.

I guess `/assign` does that,

> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **woop**
> You can assign the PR to them by writing `/assign @woop` in a comment when ready.

but apparently giving a `/lgtm` causes the bot to assign to you? Weird. The intention of how `/lgtm` is meant to work vs. `/approve` is not clear to me…

Anyway, I'm just wanting people to understand what the next step is on PRs, what they're waiting on—myself included 😅  This PR is small and a quality-of-life thing for all, I hope—how do we land it?

(I'm trying to digest #466 because we had to make a similar hack for Spark, and the changeset is a lot larger than the necessary scope because it caught up old missed formatting. So I scratched an itch I've had since December 12th, apparently 😄).

**Comment by woop** [comment]
> > I don't think we have any special use of the `assign` feature in GitHub other than for the pull request author to remind/notify the maintainers to review it.
> 
> I guess `/assign` does that,
> 
> > To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **woop**
> > You can assign the PR to them by writing `/assign @woop` in a comment when ready.
> 
> but apparently giving a `/lgtm` causes the bot to assign to you? Weird. The intention of how `/lgtm` is meant to work vs. `/approve` is not clear to me…
> 
> Anyway, I'm just wanting people to understand what the next step is on PRs, what they're waiting on—myself included  This PR is small and a quality-of-life thing for all, I hope—how do we land it?
> 
> (I'm trying to digest #466 because we had to make a similar hack for Spark, and the changeset is a lot larger than the necessary scope because it caught up old missed formatting. So I scratched an itch I've had since December 12th, apparently ).

@ches, you can have a look at the "descriptions" for these commands over here: http://prow.feast.ai/command-help

From my understanding, the `/lgtm` should come from a reviewer while the `/approve` should come from the owner that agrees to merge in the code. That being said, its very ill-defined tbh.

**Comment by ches** [comment]
> you can have a look at the "descriptions" for these commands over here: http://prow.feast.ai/command-help
> 
> From my understanding, the `/lgtm` should come from a reviewer while the `/approve` should come from the owner that agrees to merge in the code. That being said, its very ill-defined tbh.

That makes sense, thanks. The command descriptions didn't help me much, at least for `/lgtm`. Maybe it assigned to @davidheryanto after he gave a `/lgtm` _because_ he's an owner, as if to say "okay, you reviewed, so now you're a good person to take the next step too because you have approve/merge rights".

**Comment by ches** [comment]
Ah, [the other doc][1] that the bot links to covers the distinction/intent for review process better. Read that some time ago, but I guess it's sinking in now…

**Pull request merged**
