### PR TITLE
Fix installation link in README.md

### PR DESCRIPTION
**Pull request by Jeffwan**
README.md Link is broken. Should be `installing-feast.md`

### CODE REVIEW

**Comment by woop** [comment]
Thanks @Jeffwan!

Would you mind signing the [CLA](https://cla.developers.google.com/clas)? 

As soon as you do I will merge it in.

**Comment by Jeffwan** [comment]
@woop Hi, I already signed CLA. It's the similar one in Kubernetes community, right? 
https://cla.developers.google.com/about/google-individual This one?

**Comment by woop** [comment]
> @woop Hi, I already signed CLA. It's the similar one in Kubernetes community, right?
> https://cla.developers.google.com/about/google-individual This one?

Yes, thank you!

**Pull request merged**
