### PR TITLE
Use Nexus staging plugin for deployment

### PR DESCRIPTION
**Pull request by khorshuheng**
I have added Nexus Staging Plugin for deployment to Maven central, and also change the group id to dev.feast, and Java sdk client artifact id to feast-sdk.

This is a work in progress. Have tested snapshot deployment, but have not tested it by importing the sdk into a new Java project.

### CODE REVIEW

**Comment by woop** [comment]
@khorshuheng looks good. Is this mergable or should we be waiting for more commits?

**Comment by khorshuheng** [comment]
> @khorshuheng looks good. Is this mergeable or should we be waiting for more commits?

This can be merged safely, as the deploy to maven process has not been automated. The only impact of merging this would be, since i add the javadoc generation plugin, PR that has faulty Javadoc annotation will fail the tests (throw exception during package step).

With this PR one can deploy the snapshot version to OSSHR easily, using `maven clean deploy`.

There are a few things which i still need to check further, but i don't mind having them in separate PR:

1. The Java proto package starts with feast.*, the Java SDK starts with com.gojek.feast. On the other hand, our project group id is dev.feast. Perhaps we might want to be more consistent about the package naming?

2. Still need to test this manually by having a test application and import Feast SDK from Maven.

**Comment by khorshuheng** [comment]
@woop @davidheryanto 
Harded coded the parent version as property substitution is not supported: http://maven.40175.n5.nabble.com/Pom-Parent-Version-Properties-td124576.html

Deployed snapshot 0.3.6 to sonatype and dependency is resolved successfully on a new Java project:

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
    <dependency>
        <groupId>dev.feast</groupId>
        <artifactId>feast-sdk</artifactId>
        <version>0.3.6-SNAPSHOT</version>
    </dependency>
    </dependencies
```

**Pull request merged**
