### PR TITLE
Add readiness checks for Feast services in end to end test

### PR DESCRIPTION
**Pull request by davidheryanto**
Feast and Kafka services started in **test-end-to-end.sh** are not checked for readiness. Errors are only discovered during pytest runs.

This pull request add the readiness checks for those services, so failure to start any of those services will immediately fail end to end test. 

By **failing early**, it's easier to inspect the root cause of failing end to end tests.

Related to #330

### CODE REVIEW

**Comment by davidheryanto** [comment]
/hold 
Doing a bit more testing

**Comment by woop** [comment]
Is this failing because of something else?

**Comment by davidheryanto** [comment]
/hold 
Still failing due to this error
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [feast.core.model.Source]: Factory method 'getDefaultSource' threw exception; nested exception is java.lang.RuntimeException: org.apache.kafka.common.errors.TimeoutException: Aborted due to timeout.
```

**Pull request merged**
