### PR TITLE
Pin Python SDK to minor versions for dependencies

### PR DESCRIPTION
**Pull request by woop**

### CODE REVIEW

**Comment by thirteen37** [comment]
Is this absolutely necessary? Cos it's very opinioniated for a library to pin deps so strictly.

**Comment by woop** [comment]
> Is this absolutely necessary? Cos it's very opinioniated for a library to pin deps so strictly.

For some of the more mature libraries like Pandas and Numpy, probably not.

For the Google libraries, I would prefer to pin them down for now and relax them later. We're constantly running into compatibility problems with different versions of the GCP APIs, which is what in fact spurred this.

**Comment by thirteen37** [comment]
Sounds like that may lead to downstream problems for users who use other GCP libraries. Let's see.

**Comment by woop** [comment]
> Sounds like that may lead to downstream problems for users who use other GCP libraries. Let's see.

My assumption is that installation will happen within these constraints into a virtual environment. 

Anyway, I will relax some of these.

**Pull request merged**
