### PR TITLE
Ignore features in FeatureRow if it's not requested in import spec

### LINKED ISSUE #99: Ingestion is not ignoring unknown feature in streaming source
## Expected Behavior 
Ingestion should ignore feature ID in FeatureRow that was not specified in Import spec

## Current Behavior
Ingestion tried to ingest the unknown feature and throw following exception:

`"transform":"Convert feature types","message":"Unknown feature myentity.none.unknown_feature, spec was not initialized","stackTrace":"java.lang.IllegalArgumentException: Unknown feature myentity.none.unknown_feature, spec was not initialized\n\tat com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)\n\tat feast.ingestion.model.Specs.getFeatureSpec(Specs.java:148)\n\tat feast.ingestion.transform.fn.ConvertTypesDoFn.processElementImpl(ConvertTypesDoFn.java:44)\n\tat feast.ingestion.transform.fn.BaseFeatureDoFn.baseProcessElement(BaseFeatureDoFn.java:41)\n\tat feast.ingestion.transform.fn.ConvertTypesDoFn$DoFnInvoker.invokeProcessElement(Unknown Source)\n\tat org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)\n\tat org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)\n\tat org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:325)\n\tat org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)\n\tat org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)\n\tat org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:272)\n\tat org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)\n\tat org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)\n\tat org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)\n\tat org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:71)\n\tat `

## Steps to reproduce
Run ingestion with streaming source (PubSub / Kafka) and publish FeatureRow with unknown feature inside the stream.

### PR DESCRIPTION
**Pull request by pradithya**
Fix #99

### CODE REVIEW

**Comment by zhilingc** [comment]
/lgtm

thanks for adding the tests :)

**Comment by pradithya** [comment]
I agree, I think we can do it only on ConvertTypesDoFn since it's the most upstream transform.

> The only place that needs to do that is the ConvertTypesDoFn. I suggest we should instead emit the row without these suspect features, while also emit an error row (to the errors tag) with just the suspect feature.

Although, I feel emitting error row might not be a good idea since the stream might have a lot of features we are not interested at and it will just flood the error logs.

**Comment by tims** [comment]
It is probably worth emitting a special metrics for this using 
```
FeastMetrics.inc("feature:{featureId}:discarded")

**Pull request merged**
