### PR TITLE
Add minimal implementation of ingesting Parquet and CSV files

### PR DESCRIPTION
**Pull request by voonhous**
This PR tries to follow minimal implementation to ingest a parquet file using PyArrow. 
This is achieved by reading a Parquet file using PyArrow, batching it into RecordBatches before ingesting it with the existing code.

my_file.parquet → PyArrow Table → RecordBatches → Dataframe → FeatureRows (existing code) → Stream

Other modifications:
- Generator function to encode chunks of PyArrow table of type RecordBatch to yield FeatureRow objects.

### CODE REVIEW

**Comment by woop** [comment]
Thanks @voonhous 

I have two comments
1. Can you please submit all of the formatting and other changes separately? It makes it incredibly difficult to review your code if you submit 700+ lines of code difference.
2. I cant think of a good reason to wrap `ingest` with `ingest_file`. It seems like `ingest` has steps that both it and `ingest_file` should share, like validating the dataframe, getting the feature set, and inferring/applying the schema from the dataframe. These should not be rerun for every batch.

I think it would make more sense if you extended the existing `ingest` so that it took either a dataframe, path, or file-like object. You would then handle it just like in `ingest_file`. At the `infer_schema` step, a single batch can be materialized into a DF for creating the schema. Then the rest of the table is passed into `ingest_kafka` where all iteration can happen. 

What do you think?

**Comment by woop** [comment]
Also, would you mind updating the title of the PR to something more descriptive? We use the PRs as items in our change logs.

**Comment by davidheryanto** [comment]
/test test-core-and-ingestion
Trying to figure out if the integration test in feast-ingestion is flaky i.e. the test can fail with the same test configuration, specifically this test `feast.ingestion.ImportJobTest`

**Comment by woop** [comment]
I have created this code snippet which creates a testing dataframe. It has all the types besides lists of boolean. I think we should ensure that we can ingest this as both a parquet and a pandas dataframe.

https://gist.github.com/woop/d074ded542bc2b6ec5a0b5a96c72e9ab

**Pull request merged**
