### PR TITLE
Abstract bigquery

### PR DESCRIPTION
**Pull request by smadarasmi**
I wanted to add a different warehouse type (HDFS), and noticed that there are some tightly coupled usages of BigQuery. This is my attempt to abstract it. 

Please note that this is my first time using Spring Framework and I think things could have been done in a better way from my part. So please let me know if there are any suggestions or improvements on this PR and I will fix them.

### CODE REVIEW

**Comment by woop** [comment]
Hi @smadarasmi, thank you so much for the PR!

We are currently working on the 0.3-dev branch for the 0.3 release. Are you aware of the Feast 0.3 release? We will be making some significant changes to the Feast codebase, so we would need to assess where your PR would fit in. I am hoping that it can just be updated to the latest version.

Can you please join bit.ly/feast-group? Once you have joined the Feast Google Group you should have access to the Feast Google Drive which contains the latest RFC for Feast 0.3. That should give you an idea of the changes we are making.

**Comment by smadarasmi** [comment]
@woop Hey, no I was not aware of that. I will take a look at it, thanks!

**Comment by smadarasmi** [comment]
@woop I'm waiting for permission to be granted for the Feast Google Drive. Can you please help do that?

**Comment by smadarasmi** [comment]
Closing due to no longer applicable for 0.3 release.

**Comment by woop** [comment]
> Closing due to no longer applicable for 0.3 release.

Let's see how much we can reuse after the release.

**Pull request closed without merging**
