### PR TITLE
Add Telco Churn Tutorial with XGBoost and Feast

### PR DESCRIPTION
**Pull request by woop**
Adds a Telecom Churn Prediction tutorial using Feast. This tutorial will hopefully be a little bit more realistic compared to the "basic" example that we have.

### CODE REVIEW

**Comment by zhilingc** [comment]
Can we host the file instead of pushing it to the repository?

**Comment by woop** [comment]
> Can we host the file instead of pushing it to the repository?

Sure, I was planning to drop it on nbviewer like this: https://nbviewer.jupyter.org/github/woop/feast/blob/add-churn-prediction-tutorial/examples/feast-xgboost-churn-prediction-tutorial/Telecom%20Customer%20Churn%20Prediction%20%28with%20Feast%20and%20XGBoost%29.ipynb

Or did you have something else in mind?

**Comment by zhilingc** [comment]
No, I mean the data file.

**Comment by woop** [comment]
> No, I mean the data file.

Sure, I can push it to GCS. It's pretty small though. 1mb vs the Feast repo that is 16mb.

**Comment by zhilingc** [comment]
> > No, I mean the data file.
> 
> Sure, I can push it to GCS. It's pretty small though. 1mb vs the Feast repo that is 16mb.

You're making it 1mb bigger though 🤔 it's already brutal pulling this repository on a bad connection

**Comment by woop** [comment]
@zhilingc I've moved the data out. Will merge this.

**Pull request merged**
