### PR TITLE
Ensure ImportJobTest is not flaky by checking WriteToStore metric and requesting adequate resources for testing

### PR DESCRIPTION
**Pull request by davidheryanto**
**feast.ingestion.ImportJobTest** sometimes fail unpredictably because not all the keys ingested in Redis are found during retrieval, but the test log does not provide useful info for debugging the failure. 

Example of such [error](http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/pr-logs/pull/gojek_feast/327/test-core-and-ingestion/1199291472017362944):
```
runPipeline_ShouldWriteToRedisCorrectlyGivenValidSpecAndFeatureRow

  java.lang.AssertionError: 
  Key not found in Redis: ...
```

This pull request:
1. Adds a **check whether the ingestion job has finished writing elements** by checking the metric for no of elements written to the store periodically. Only when this counter no longer changes, the correctness of the ingested FeatureRow is evaluated. Previously the check is based on a fixed amount of duration (which is less reliable due to the the variability in the resources and input samples in the running environment)

> The reason for using metric utility for this check is because the pipeline is a streaming pipeline with 
> unbounded source. Hence, the pipeline is always running or failed, i.e. no completed succesfully 
> state to check when it has ingested all the Feature Row.
> 
> Beam built in metric utility is used here (so it has no external dependencies on external metric collectors, such as statsd or prometheus) and this metric counts the no elements
> **WriteToStore** transform has processed.
> https://beam.apache.org/documentation/programming-guide/#metrics

2. Adds **resources request** for the Pod running the test. Previously, the resources that the test Pod get assigned depends on how overloaded the test cluster is. By having a guaranteed amount of CPU and memory, the duration of tests should be more predictable.

3. Adds more **debugging info when such test fails**:
- Printing the output of redis [INFO](https://redis.io/commands/info). This is useful for e.g. to check the count of keys ingested. If the count is fewer than expected, probably, we need to let ingestion job runs a bit longer because it hasn't fully ingested the complete sample input data.
- Printing one random sample of element in Redis, to check that at least some FeatureRow is correctly ingested.

These should ensure `ImportJobTest` test result is reproducible.

### CODE REVIEW

**Comment by woop** [comment]
Thanks for this @davidheryanto 

Should we perhaps rename the PR to be more descriptive? Its not clear that this ensures any less flakyness.

**Comment by davidheryanto** [comment]
/hold
Need to update PR title and consider tracking the ingestion progress.

**Comment by davidheryanto** [comment]
/hold cancel
Updated PR title and add check for WriteToStore metrics

**Pull request merged**
