### PR TITLE
Helm Chart Upgrades

### PR DESCRIPTION
**Pull request by Yanson**
**What this PR does / why we need it**:

- Move prometheus-statsd-exporter to toggleable core dependency (default false).
- Add ingresses for gRPC and HTTP for both core and serving.
- Refactor ConfigMaps to user Spring profiles rather than manipulating the base application.yaml.
- Add ability to define and enable arbitrary Spring profiles.
- Add toggle to enable prometheus scraping in core.
- Add parameters to change LOG_LEVEL and LOG_TYPE (#430).
- Add parameter to specify GOOGLE_CLOUD_PROJECT.
- Allow jar path to be specified (e.g. if using non-standard image).
- Add missing documentation for Helm parameters.

**Which issue(s) this PR fixes**:
General improvements that we have had use-cases for. Please ask if the reason for any of the changes are unclear.

**Does this PR introduce a user-facing change?**:

```release-note
If deploying with Helm, review and reconfigure values file as necessary.
```

To compare the Helm output of these changes with the previous version, these commands can be used.

```bash
helm install --dry-run --debug feast-charts/feast --name demo -f infra/charts/feast/values-demo.yaml > scratch/helm-install.demo.old.yaml

helm install --dry-run --debug ./infra/charts/feast --name demo -f infra/charts/feast/values-demo.yaml > scratch/helm-install.demo.new.yaml
```

### CODE REVIEW

**Comment by woop** [comment]
Thanks @Yanson!

I believe @davidheryanto wants to move from `prometheus-statsd-exporter` to `telegraf`. 

@davidheryanto can we make a decision on which to use here?

**Comment by davidheryanto** [comment]
I'm ok with using either StatsD exporter. Although it seems `prometheus-statsd-exporter` is no longer in `stable` or `incubator` helm charts repository:
- https://github.com/helm/charts/tree/master/stable/
- https://github.com/helm/charts/tree/master/incubator 

But I think it's OK since we can put the `prometheus-statsd-exporter` chart in Feast repo. I'll review your changes. I think we can use `prometheus-statsd-exporter` for now.

Thanks for the PR.

**Comment by Yanson** [comment]
Just to be clear, `prometheus-statsd-exporter` was already in the Feast repo, all I did was move it from the top level to core (as it's only used by core) and add a flag of whether to install it or not.

Internally we use a "vanilla-service" chart that can deploy almost anything, so used that to deploy statsd-exporter. If you would rather have a dependency than keep the chart in this repo (which is sensible), I can share details of its use (it is already public).

Regarding telegraf, I don't know much about it, bt my [opinion](https://github.com/gojek/feast/pull/449#issuecomment-579718657) is to stick to standard Beam metrics. Though, this discussion is outside the scope of this PR (which does not preclude such changes down the road).

The other changes are more "interesting".

**Pull request merged**
