### PR TITLE
Fixes #31 - errors during kafka deserializer (passing) test execution

### LINKED ISSUE #31: Errors during kafka deserializer (passing) test execution
Below error is thrown while running the kafka deserializer test, even though the test passes, which could break the build
`Caused by: java.io.FileNotFoundException: /var/folders/kd/yyfwdyk15b32xdjs1j9j3qsr0000gp/T/kafka-5510291321770207219/topic-3198cdeb-d825-4092-8c6d-bd27db077c5c-0/00000000000000000001.snapshot (No such file or directory)`

### PR DESCRIPTION
**Pull request by baskaranz**
This fixes the error being thrown by the test, which breaks the build, although the test passes.

### CODE REVIEW

**Comment by woop** [comment]
@baskaranz can you please squash the commits and also create an issue for this PR?

**Comment by tims** [comment]
I'd be interested to know why this fixed the warnings?

**Comment by baskaranz** [comment]
@tims I've used google-java-format plugin and it didn't reformat my code to keep ContextConfiguration at the bottom.

Coming to the fix, I've seen multiple issue raised even with spring and other forums about the same issue, which stated that it fails their jenkins build etc., (assuming we would face the same as well) Here's one 

https://github.com/spring-projects/spring-kafka/issues/194

I've used `@ClassRule` for KafkaEmbedded instead of bean and it resolved the ERROR messages I see while running the test

**Comment by tims** [comment]
Make sure it's enabled for your project, you need turn it on, not just install it.

**Comment by baskaranz** [comment]
@tims Intelij was smart enough to suggest me when I installed the plugin to enable for my projects and I did, not sure why it doesn't reorganize the code when it reformats :)

**Comment by tims** [comment]
Sorry to keep harping on about it, but formatting changes in every commit will continue to drive us nuts.

I've found I need to enable for every project separately, it's not global, so you may have enabled for another project?

Can you check preferences -> other settings -> google-java-format settings
And ensure Enable google-java-format is checked.
And make sure you've restarted intellij since installing. 

Then run cmd-alt-shift-L in the file (assuming on osx)

**Comment by woop** [comment]
> Sorry to keep harping on about it, but formatting changes in every commit will continue to drive us nuts.
> 
> I've found I need to enable for every project separately, it's not global, so you may have enabled for another project?
> 
> Can you check preferences -> other settings -> google-java-format settings
> And ensure Enable google-java-format is checked.
> And make sure you've restarted intellij since installing.
> 
> Then run cmd-alt-shift-L in the file (assuming on osx)

Should we make an issue for creating a `contributing` document again? Where we can specify how your development environment should be set up for contributing to each component?

**Comment by woop** [comment]
@baskaranz you mind squashing this into atomic commits?

**Comment by woop** [comment]
The test wont pass until a rebase is done on current master. Also, @pradithya can you please review this instead of me? You have more familiarity.

**Comment by pradithya** [comment]
@baskaranz  Is it possible to remove dependency to `org.springframework.kafka` for testing in the future?

**Comment by pradithya** [comment]
@baskaranz  @tims the import ordering is not handled by google-java-format plugin, you'll need to import [google code style for intelliJ](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) to your code style settings.

**Comment by tims** [comment]
/lgtm

@pradithya since org.springframework.kafka snuck in with a previous pull request, I'm okay if we make 
a new issue to remove it. But I'll defer to you.

**Pull request merged**
