### PR TITLE
<doc>(README): add a link for user to view docs on GitBook

### PR DESCRIPTION
**Pull request by david30907d**
add a link for user to view docs on GitBook

### CODE REVIEW

**Comment by david30907d** [comment]
> We're not currently a part of Kubeflow, so not sure about linking to them yet.

Oh, i'm sorry i know `Feast` is not part of kubeflow. I'm just want to use the same phrase of `Kubeflow` from its README but forgot to replace `kubeflow.org` with `https://feast.dev`.

Sorry for the offense 😓

**Comment by woop** [comment]
> > We're not currently a part of Kubeflow, so not sure about linking to them yet.
> 
> Oh, i'm sorry i know `Feast` is not part of kubeflow. I'm just want to use the same phrase of `Kubeflow` from its README but forgot to replace `kubeflow.org` with `https://feast.dev`.
> 
> Sorry for the offense

Haha, no worries. Thanks for contributing!!

Would you mind signing the Google CLA before I merge this in?

https://cla.developers.google.com/clas

**Comment by david30907d** [comment]
> > > We're not currently a part of Kubeflow, so not sure about linking to them yet.
> > 
> > 
> > Oh, i'm sorry i know `Feast` is not part of kubeflow. I'm just want to use the same phrase of `Kubeflow` from its README but forgot to replace `kubeflow.org` with `https://feast.dev`.
> > Sorry for the offense
> 
> Haha, no worries. Thanks for contributing!!
> 
> Would you mind signing the Google CLA before I merge this in?
> 
> https://cla.developers.google.com/clas

sure, i would sign it right now~

**Comment by david30907d** [comment]
@woop i'm done~

**Pull request merged**
