### PR TITLE
Auto format to Google style with Spotless

### PR DESCRIPTION
**Pull request by ches**
We state in the contributing guide that we conform to Google Java style, but actually we don't. This applies [the Spotless Maven plugin][1] which runs the Google formatter automatically.

The plugin can also take care of license headers, I didn't enable that yet but I can if you'd like.

This is obviously opinionated, I went ahead and sent this PR to open discussion because actually writing the change took 5 minutes, I won't be hurt if we don't use it. Also I thought that just after cutting 0.3 may be as opportune a time as it gets, hopefully not too many branches/PRs in flight that will suffer merge conflicts from a mass formatting application.

Having coding standards checks run automatically in the build adds a bit of friction for contributing. Automation though is arguably favorable to human reviewers remarking subjectively about such matters, for both parties. Measures can be taken to make the CI experience as pleasant as possible, suggesting how to fix infractions and resubmit.

Personally, I don't write Java everyday, so I don't have a tuned sense of what a lot of constructs should idiomatically "look like" and I appreciate it being answered for me, but I warmed to auto-formatting years ago so I'm biased.

As one point of precedent, the Beam project uses Spotless in their build. Of course in the Kubernetes ecosystem like Kubeflow, `go fmt` is ubiquitous and we mention it for the Feast Go SDK.

[1]: https://github.com/diffplug/spotless/tree/master/plugin-maven

### CODE REVIEW

**Comment by woop** [comment]
> We state in the contributing guide that we conform to Google Java style, but actually we don't. This applies [the Spotless Maven plugin](https://github.com/diffplug/spotless/tree/master/plugin-maven) which runs the Google formatter automatically.
> 
> The plugin can also take care of license headers, I didn't enable that yet but I can if you'd like.
> 
> This is obviously opinionated, I went ahead and sent this PR to open discussion because actually writing the change took 5 minutes, I won't be hurt if we don't use it. Also I thought that just after cutting 0.3 may be as opportune a time as it gets, hopefully not too many branches/PRs in flight that will suffer merge conflicts from a mass formatting application.
> 
> Having coding standards checks run automatically in the build adds a bit of friction for contributing. Automation though is arguably favorable to human reviewers remarking subjectively about such matters, for both parties. Measures can be taken to make the CI experience as pleasant as possible, suggesting how to fix infractions and resubmit.
> 
> Personally, I don't write Java everyday, so I don't have a tuned sense of what a lot of constructs should idiomatically "look like" and I appreciate it being answered for me, but I warmed to auto-formatting years ago so I'm biased.
> 
> As one point of precedent, the Beam project uses Spotless in their build. Of course in the Kubernetes ecosystem like Kubeflow, `go fmt` is ubiquitous and we mention it for the Feast Go SDK.

Good points @ches 

Another one to note is that we are using https://pypi.org/project/black/ for formatting Python code. I'm quite in favor of having these tools take over completely, especially during submission of PRs. I also think adding it for the license headers makes sense.

**Comment by woop** [comment]
@ches if you can refresh this then I will approve it. Sorry for the delay.

**Comment by ches** [comment]
No worries. Rebased and added the license header support for Java files.

Removing blank lines between existing headers and `package` declarations was not intentional, but I couldn't quickly figure out how to preserve them. A literal newline in the `CDATA` didn't work, Spotless is doing an equivalent of `strip` or `trim` somewhere I would guess.

**Comment by woop** [comment]
/retest 

We really need to fix these tests :(

**Pull request merged**
