### PR TITLE
Add docker-compose for Feast

### PR DESCRIPTION
**Pull request by kaihendry**

### CODE REVIEW

**Comment by woop** [comment]
Would you mind renaming this to capture the contents of the PR? That makes it easier for us to build change logs later. 

You can look at the following for closing an issue based on a PR
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by kaihendry** [comment]
Tested like so:

```[hendry@t480s ~]$ grpc_cli ls localhost:6565
grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection
feast.core.CoreService

[hendry@t480s ~]$ grpc_cli ls localhost:6566
grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection
feast.serving.ServingService
```

Updated the commit message btw

**Comment by woop** [comment]
@kaihendry, minimally we need to ensure that ingestion and retrieval works for this to be merged in.

**Comment by kaihendry** [comment]
I'm not how to test that. I also investigating in parallel some sort of automated testing. https://stackoverflow.com/questions/59024442/best-practices-for-docker-compose-testing

**Comment by woop** [comment]
@kaihendry I think we should close this PR in favour of this one: #328

**Pull request closed without merging**
