### PR TITLE
Fix integration testing config

### PR DESCRIPTION
**Pull request by zhilingc**
1. Added rerun command and corrected trigger command
2. Fixed integration test image

### CODE REVIEW

**Comment by thirteen37** [comment]
Related to #102?

**Comment by zhilingc** [comment]
@thirteen37 No, this fixes some issues with the running of the integration test via CI. The triggering is already working as intended, although the integration test step is not properly throwing an error when the test fails. The changes made in this commit should fix that.

See the latest postsubmit-integration-test here: http://prow.feast.ai/

**Comment by thirteen37** [comment]
@zhilingc Sounds like you're saying that #102 is actually resolved then? Can we mark it as such or is there more work remaining?

**Comment by zhilingc** [comment]
@thirteen37 Not quite, I need this fix in so that it does throw an error when one occurs, otherwise the integration test (that does the building of the binaries) will always pass

**Comment by davidheryanto** [comment]
Closed by #197

**Pull request closed without merging**
