### PR TITLE
Simplify and document CLI building steps

### PR DESCRIPTION
**Pull request by thirteen37**
Try to reduce the complexity of getting the development dependencies necessary for building the CLI and update the README with these new steps.

### CODE REVIEW

**Comment by tims** [comment]
@woop didn't you want to rewrite this in python?

**Comment by woop** [comment]
> @woop didn't you want to rewrite this in python?

Correct. I think rewriting this in Python would make a lot of sense. So it can be seen as a tech debt, but it's not a high priority right now. I think our focus should be more on hygiene (docs, tests, packaging).

**Pull request merged**
