### PR TITLE
Rename metric name for request latency in feast serving

### PR DESCRIPTION
**Pull request by davidheryanto**
**What this PR does / why we need it**:
So that it is consistent with the actual unit of timing being measured.
And recommended metric names in Prometheus https://prometheus.io/docs/practices/naming/#metric-names
**Which issue(s) this PR fixes**:

NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidheryanto** [comment]
/hold
Checking why test fails

**Comment by davidheryanto** [comment]
Test fails because several hours ago `fastavro` is updated to **0.22.10** and this line wil fail
```
to_avro(df=features_1_df[["event_timestamp", "entity_id"]], file_path_or_buffer=file_name)
```

with this error
```
TypeError: Timestamp subtraction must have the same timezones or no timezones
```

2 potential fixes:
- Fix the fastavro version to 0.22.9
- Do not specify timezone in the end-to-end test sample data

```diff
- time_offset = datetime.utcnow().replace(tzinfo=pytz.utc)
+ time_offset = datetime.utcnow().replace(tzinfo=None)
```

**Comment by woop** [comment]
Can we merge this @davidheryanto ?

**Comment by davidheryanto** [comment]
/hold cancel
Yes the master already fix fastavro version to 0.22.9
I forgot to cancel the hold label

**Pull request merged**
