### PR TITLE
Kafka IO fixes

### PR DESCRIPTION
**Pull request by tims**
fixes for #22

### CODE REVIEW

**Comment by tims** [comment]
@baskaranz

**Comment by tims** [comment]
No it shouldn't. Anything that makes use of GCP resources like BQ or GCS should pick up credentials from the environment automatically. 

For Flink in particular, we expect it's mostly likely to be used when you aren't using GCP at all. So in that case you definitely don't need to set it.

**Comment by tims** [comment]
@baskaranz @woop can you review this when you get a chance so we can merge?

**Comment by baskaranz** [comment]
@tims 

Thought of checking on earlier comment to make myself clear

`For Flink in particular, we expect it's mostly likely to be used when you aren't using GCP at all. So in that case you definitely don't need to set it.`

The use case we would be using flink-runner is, when ingesting data from `kafka topic(s)` to `BQ warehouse store` and `redis serving store`, so flink-runner wouldn't need (or use) the GCP credentials to write to BQ in this scenario?

**Pull request merged**
