### PR TITLE
Add support for storing spring profiles as kubernetes secrets

### PR DESCRIPTION
**Pull request by pmjacinto**
**What this PR does / why we need it**:

- Adds support for storing spring profiles as kubernetes secrets (e.g. database connection strings)
- Enables automatic deployment rollout when the configuration changes ([using helm](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments))
- Moves `store.yaml` into a new configmap as it does not require a pod restart to reload

**Which issue(s) this PR fixes**:

General reliability improvements.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
`feast-*.springSecretProfiles` and `feast-*.springSecretProfilesActive` were added to `values.yaml`. No helm chart values update required in order to keep the current behaviour.

To compare the Helm output of these changes with the previous version, these commands can be used.

```
helm install --dry-run --debug feast-charts/feast --name demo -f infra/charts/feast/values-demo.yaml > scratch/helm-install.demo.old.yaml

helm install --dry-run --debug ./infra/charts/feast --name demo -f infra/charts/feast/values-demo.yaml > scratch/helm-install.demo.new.yaml
```

### CODE REVIEW

**Comment by woop** [comment]
Thanks for the submission @pmjacinto! 

Quick question: Have you signed the CLA?

**Comment by pmjacinto** [comment]
> Thanks for the submission @pmjacinto!
> 
> Quick question: Have you signed the CLA?

Hey @woop 

Yes, I've signed the google CLA.

**Comment by woop** [comment]
Haven't had time to review this yet. Please bear with us :)

**Comment by woop** [comment]
@pmjacinto would be great to get your take on #533. Especially because it now tries to solve the secrets problem as well.

**Comment by woop** [comment]
@pmjacinto I believe this functionality is now covered by #533. Please let us know if you think it should be reopened. Really do appreciate the effort you put in here.

**Pull request closed without merging**
