### PR TITLE
Regenerate go

### PR DESCRIPTION
**Pull request by zhilingc**
Update generated go protos.

### CODE REVIEW

**Comment by tims** [comment]
Can we automate this in the build? We should never have to remember this

**Comment by tims** [comment]
Eg for Go, we could make it regenerate the code and if it differs the merge should be aborted because of uncommitted changes

Python gen code should not be committed, it should be generated before we package wheels

**Comment by woop** [comment]
> Eg for Go, we could make it regenerate the code and if it differs the merge should be aborted because of uncommitted changes
> 
> Python gen code should not be committed, it should be generated before we package wheels

Does this require an issue in itself?

**Pull request merged**
