### PR TITLE
Release v0.3.7

### PR DESCRIPTION
**Pull request by woop**
**What this PR does / why we need it**:

Releases v0.3.7. I am not sure how much we need this release, but the point is to test out the release process as a wet run of #476.

### CODE REVIEW

**Comment by woop** [comment]
@ches I'm not sure if I have the time to debug the issues on this branch. Are we confident in the changes that have been backported? I think the problem here is likely more the tests/CI than the code.

**Comment by ches** [comment]
I thought we had a passing build on #654 and/or #657, I'll take a look at it here.

> I am not sure how much we need this release

`datatypes-java` being published to Central is essential for me to publish an open source release of Scala SDK with the v0.3 support that we use in production. This will close #442 if no one much cares about the v0.3.6 artifacts.

**Comment by woop** [comment]
`Error: Unable to access jarfile core/target/feast-core-*-SNAPSHOT.jar`

It's looking for the `-SNAPSHOT` I think

**Comment by woop** [comment]
Alright, seems fine now. The non-snapshot jar finding needs to be forward ported as well to master.

**Comment by ches** [comment]
The changelog generation seems slightly off, mostly the 0.3.7 release version itself: its "Full Changelog" link is compare of https://github.com/gojek/feast/compare/v0.4.7...v0.3.7 instead of v0.3.6...v0.3.7, which actually includes the Cassandra store, and adding indexes.

There's also a reference to #375 that actually links to 376, not sure if that might have been a mistake in a human edit.

**Comment by woop** [comment]
> The changelog generation seems slightly off, mostly the 0.3.7 release version itself: its "Full Changelog" link is compare of [v0.4.7...v0.3.7](https://github.com/gojek/feast/compare/v0.4.7...v0.3.7) instead of v0.3.6...v0.3.7, which actually includes the Cassandra store, and adding indexes.
> 
> There's also a reference to #375 that actually links to 376, not sure if that might have been a mistake in a human edit.

I noticed the first problem as well when I created the GitHub release. Will try and figure out why that happened.

The rest of the changelog was copied over from master. I only generated the 0.3.7 contents.

**Pull request merged**
